### ISSUE TITLE
Bug with Threading

### ISSUE THREAD

**Issue by dlahmad** [Ellerbach/serialapp#10]
Hello @Ellerbach ,

thanks for your good work with this serial port implementation!

 I found a possible error source in your implementation. In your SerialDevice.cs in the open() method you wrote
```
Task.Run((Action)StartReading, CancellationToken);
this.fd = fd;
```
while it should be 
```
this.fd = fd;
Task.Run((Action)StartReading, CancellationToken);
```
because of threading issues. It can happen that the newly started thread checks

```
if (!fd.HasValue)
{
    throw new Exception();
}
```
and ends with exception because "this.fd = fd;" has not been set at the time. This indeed happend to me. Switching the instructions solved the problem.

Could you please fix this?

Best Regards

**Comment by Ellerbach** [comment]
Thanks for the input, you're absolutly correct. I'm fixing the code right now and will update the repo as well as the nuget package.

**Comment by Ellerbach** [comment]
Repo updated with the changes and new nuget submitted (should be available very soon). Thanks again for pointing out the issue.
