### ISSUE TITLE
Garble or high CPU

### ISSUE THREAD

**Issue by rtjaden** [Ellerbach/serialapp#11]
I have tried both methods, using bluetooth. Using a Pi 3b+ I bind the remote bluetooth module (ESP32) with the rfcomm tool, then refer to /dev/rfcomm0 in the c# code instead of ttyS0, etc. It mostly works (see below), but I'm running into the following:

- First method works good with receiving on the Pi, no strange stuff, and is decent on CPU usage (about 5%). However something (the so library?) on the pi sends random bytes (it seems) to the esp32 module, even when I'm not sending anything explicitly in code. 

- The second method works flawlessly in receiving and sending (no random garble being sent to the esp32), however it consumes 50-60% cpu time on the pi, which is too much to make it useful. It even consumes this when I just open de port and literally do nothing else in the code (no sending or receiving). 

Any pointers would be great, since these are the only two methods I came across to make it work in .Net core. The pi and esp32 work fine in Nodejs for example, but the threading model is too limited for my purposes that way. 
Thanks

**Comment by Ellerbach** [comment]
Hi,
I would have to try the configuration and try to understand what is happening. The Library used for the first method is the main libc. so there is Nothing specific for this one. 
For the second method, I'm just the Messenger here as I'm not part of the dev team. You can try to contact them.
There is another new method existing that you can try, it's native support of SeriaPort in .NET Core 2.1. See: https://github.com/dotnet/iot

Couple of questions:
- are you using the native Bluetooth driver for the RPI?
- what Bluetooth service are you using? just serial?

**Comment by rtjaden** [comment]
Hi,
Thanks for responding. 
* I am just using the standard debian/raspbian distro. I guess that is the native BT driver? I use the rfcomm utility to bind to BT address of the esp32 first. This results in the device /dev/rfcomm0, which I then plug into the sample code. I do literally nothing else (but remove the write calls for testing). 
* Just the serial service yes. 

I will try the .net core version, but it seemed to be very preview, so was looking for something more production ready. 

I just don't get why the first method sends these random bytes back to the esp32 (I removed all write calls). If I stop the sample program, the garble stops as well, so its something in there, just can't figure it out.

**Comment by rtjaden** [comment]
Update: I tried the iot preview, but it seems to be GPIO only. No serial implementation (for linux). And the only reason that I'm using linux is that Windows IoT Core somehow refuses to support graphical acceleration for the Pi, which made my UWP prototype so slow as to be unacceptable. Using any other board would make the end product too expensive to sell. Sorry, I'll get of my soap box now. 

On a bright note though, after making some small change on the ESP32, somehow the random garble seems to have disappeared for the first solution. Bit puzzled as to why. I only changed it in a seemingly insignificant way, but it's gone 👍 

Guess you can close the issue, back to an acceptable 5% cpu usage. If anyone wants to see the exact change, I can post/send my code. 
Thanks again.

**Comment by Ellerbach** [comment]
Thanks for the update! On the .NET Core project, the serial port is available as well. And it uses the same principle as the first method you are using.
And really happy it is working for you and you fond the issue.
Enjoy :-)
