### ISSUE TITLE
Receiving works, but not sending

### ISSUE THREAD

**Issue by teseosoft** [Ellerbach/serialapp#12]
Hello @Ellerbach !

Thank you for your work!

I have been testing it to send data from the Raspberry Pi3 GPIO and I can receive data, but the sent data does not arrive to my other testing PC.
This is the simple code I use for the test:
```
Dim mySer As IO.Ports.SerialDevice = New IO.Ports.SerialDevice("/dev/ttyS0", IO.Ports.BaudRate.B115200)
AddHandler mySer.DataReceived, AddressOf DataRec
mySer.Open()
While (Not Console.KeyAvailable)
    Dim MySerialText As String = Date.Now.ToString("dd/MM/yyyy HH:mm:ss")
    Dim buf As Byte() = System.Text.Encoding.ASCII.GetBytes(MySerialText)
    Console.WriteLine("Sending: " & MySerialText)
    mySer.Write(buf)
    Threading.Thread.Sleep(500)
End While
Console.WriteLine("Closing port")
mySer.Close()
```

As I said, it works receiving the data, but not sending.
I tested a loopback joining the Raspberry TX and RX pins and nothing is received, but the curious thing is that if I do this loopback test from python it works, and after it, it also works with my code, so I am wondering if I am missing a "wake up call" to the serial sending port or something like that.
Could you please help me?

This is the python code that "wakes" the serial port and after it my code also works:

```
#!/usr/bin/env python
import time
import serial
ser = serial.Serial(
               port='/dev/ttyS0',
               baudrate = 115200,
               parity=serial.PARITY_NONE,
               stopbits=serial.STOPBITS_ONE,
               bytesize=serial.EIGHTBITS,
               timeout=1
           )
counter=0
while 1:
               ser.write('Write counter: %d \n'%(counter))
               time.sleep(1)
               counter += 1
```
Thanks!

**Comment by Ellerbach** [comment]
Hi, that look very weird inded. If the console is not desable, it can create those kind of issues. Did you remove the console from the boot options?
https://github.com/Ellerbach/serialapp#enabling-the-uart

**Comment by teseosoft** [comment]
Thank you for your quick answer!

Yes, in principle the boot options are ok. I did it from the Raspberry GUI options, but I have checked the files and everything seems correct.
If you think about any other option I will be more than grateful...

/boot/cmdline.txt 
```
dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p7 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait splash plymouth.ignore-serial-consoles quiet
```

/boot/config.txt (commented lines removed)
```
hdmi_force_hotplug=1

hdmi_group=2
hdmi_mode=85

dtparam=audio=on

hdmi_force_hotplug=1

max_usb_current=1
hdmi_group=2
hdmi_mode=85
hdmi_cvt 1024 600 60 6 0 0 0
hdmi_drive=1
enable_uart=1
```

Also, just in case it helps, this is the output of my code before "waking up" the port:
```
Sending: 16/04/2019 14:47:20
Sending: 16/04/2019 14:47:20
Sending: 16/04/2019 14:47:21
Sending: 16/04/2019 14:47:21
Sending: 16/04/2019 14:47:22
Sending: 16/04/2019 14:47:22
```

Then I "wake it up" with the python code, close it, and when I launch again my code the output is:
```
Received: 
Received: 
Sending: 16/04/2019 14:48:02
Received: 16/04/2019 14:48:02
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Sending: 16/04/2019 14:48:03
Received: 16/04/2019 14:48:03
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Sending: 16/04/2019 14:48:03
Received: 16/04/2019 14:48:03
Received: 
```

As you can see it seems that is like is receiveing information all the time...

Thank you for your help!

**Comment by Ellerbach** [comment]
Well, looks like the serial port is correctly setup in the cmdline and config files. 
So only other option I can see is the right on the port. Have you checke that you have the right to read and write on the port? Have you try to run your code with sudo?

**Comment by Ellerbach** [comment]
So I've tested the code on a RPI3, with .NET Core 2.2, same code as you did:

```vb
Imports System

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
        Dim mySer As IO.Ports.SerialDevice = New IO.Ports.SerialDevice("/dev/ttyS0", IO.Ports.BaudRate.B115200)
        AddHandler mySer.DataReceived, AddressOf DataRec
        mySer.Open()
        While (Not Console.KeyAvailable)
            Dim MySerialText As String = Date.Now.ToString("dd/MM/yyyy HH:mm:ss")
            Dim buf As Byte() = System.Text.Encoding.ASCII.GetBytes(MySerialText)
            Console.WriteLine("Sending: " & MySerialText)
            mySer.Write(buf)
            Threading.Thread.Sleep(500)
        End While
        Console.WriteLine("Closing port")
        mySer.Close()
    End Sub

    Private Sub DataRec(arg1 As Object, arg2() As Byte)
        Console.WriteLine("Received: " & System.Text.Encoding.UTF8.GetString(arg2))
    End Sub
End Module
```

I used ```dotnet publish -r linux-arm``` to create a publish directory and copied the directory to the RPI.
I changed the mode for the ./ConsoleApp1 that is in the directory and executed in non admin mode. The default permission on the serial port do not allow me to access it. Which is the expected behavior.

```pi@rpinetcore:~/vb $ sudo chmod +x ./ConsoleApp1
pi@rpinetcore:~/vb $ ./ConsoleApp1
Hello World!

Unhandled Exception: System.Exception: failed to open port (/dev/ttyS0)
   at System.IO.Ports.SerialDevice.Open()
   at ConsoleApp1.Program.Main(String[] args) in C:\tmp\vbtest\ConsoleApp1\ConsoleApp1\Program.vb:line 8
Aborted
```

so I ran it in sudo mode:
```
pi@rpinetcore:~/vb $ sudo ./ConsoleApp1
Hello World!
Sending: 17/04/2019 17:45:57
Received: 1
Received: 7/04/2019 17:45:57
Sending: 17/04/2019 17:45:57
Received: 17
Received: /04/2019 17:45:57
Sending: 17/04/2019 17:45:58
Received: 17
Received: /04/2019 17:45:58
Sending: 17/04/2019 17:45:58
Received: 17
Received: /04/2019 17:45:58
Sending: 17/04/2019 17:45:59
Received: 17
Received: /04/2019 17:45:59
Sending: 17/04/2019 17:45:59
Received: 17
Received: /04/2019 17:45:59
Sending: 17/04/2019 17:46:00
Received: 17/
Received: 04/2019 17:46:00
Sending: 17/04/2019 17:46:00
Received: 17/
Received: 04/2019 17:46:00
Sending: 17/04/2019 17:46:01
Received: 17/
Received: 04/2019 17:46:01
Sending: 17/04/2019 17:46:01
Received: 17/
Received: 04/2019 17:46:01
Sending: 17/04/2019 17:46:02
Received: 17
Received: /04/2019 17:46:02
Sending: 17/04/2019 17:46:02
Received: 17/
Received: 04/2019 17:46:02
```

So it's exactly the expected behavior.

You still can have some output going into the serial port.
See https://elinux.org/RPi_Serial_Connection
Especially this part:
Secondly, after booting, a login prompt appears on the serial port. This is controlled by the following lines in /etc/inittab:
#Spawn a getty on Raspberry Pi serial line
T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100
You will need to edit this file to comment out the second line, i.e. 
#T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100
Finally you will need to reboot the Raspberry Pi for the new settings to take effect. Once this is done, you can use /dev/ttyAMA0 like any normal Linux serial port, and you won't get any unwanted traffic confusing the attached devices. 
The above instructions have been verified on Raspbian 'Wheezy'; other distributions may be set up differently. To double-check, use 
cat /proc/cmdline
to show the current kernel command line, and 
ps aux | grep ttyAMA0

So as I guess, your issue is most likely a right access problem plus not fully deactivating all what is going in/out of the serial port.

Let me know

**Comment by Ellerbach** [comment]
If you see something when running ```ps aux | grep ttyS0``` like this
```
root       523  0.0  0.1   3960  1868 ttyS0    Ss+  18:27   0:00 /sbin/agetty --keep-baud 115200,38400,9600 ttyS0 vt220
pi         592  0.0  0.0   4368   536 pts/0    S+   18:28   0:00 grep --color=auto ttyS0
``` 

Run the Following commands:
```
sudo systemctl stop serial-getty@ttyS0.service
sudo systemctl disable serial-getty@ttyS0.service
```

You can as well fully disable those services from the service and you will have the serial port just for you :-)

**Comment by teseosoft** [comment]
Thanks a lot for all the information!
It looks promising and I hope that I will be able to solve it!
Unfortunately I have no access to the RPI until next Tuesday, buy I will post the result once I try it.
Thanks again! I really appreciate the help!

**Comment by Ellerbach** [comment]
> It looks promising and I hope that I will be able to solve it!

I really hope so :-) and to fully remove the serial port used as a console, edit the file ```sudo nano /var/run/systemd/generator/getty.target.wants/serial-getty@ttyS0.service``` and just place a # in front of the line : ```# ExecStart=-/sbin/agetty --keep-baud 115200,38400,9600 %I $TERM``` you can comment as well the Restart line. That's quick fix to see if after stopping the services and running the code again things are working. Later on, you can fully remove this service.

**Comment by Ellerbach** [comment]
And last point, this code was release far before an official support for System.IO.Ports arrived for .NET Core 2.2: https://github.com/dotnet/corefx/tree/master/src/System.IO.Ports/src/System/IO/Ports
So you may prefer the official implementation. And if you look at the source code, it is very close to what I4ve been doing. The official one implements more elements.

**Comment by teseosoft** [comment]
Hello again!

I fear I have no good news... everything stays the same.
The code works exactly the same executing it as sudo or with normal privileges.
I would say I have the correct rights in the port (I am a member of the dialout group):
```
pi@raspberrypi:~ $ ls -l /dev/ttyS0
crw-rw---- 1 root dialout 4, 64 Apr 23 09:14 /dev/ttyS0
```

And nothing else seems to be using the port:
```
pi@raspberrypi:~ $ ps aux | grep ttyS0
pi         954  0.0  0.0   4368   532 pts/2    S+   09:31   0:00 grep --color=auto ttyS0
```

About using the official System.IO.Ports, as far as I know it does not yet support linux, but it will in .Net Core 3 (I tried it anyway just in case and it is confirmed):
```
Unhandled Exception: System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort.GetPortNames()
   at TestSerial.Program.Main(String[] args) in C:\...\TestSerial\TestSerial\Program.vb:line 85
Aborted
```

To be sure that it was not a HW issue, I also tested it with another RPI3.
Before the test, I updated it:
```
sudo apt-get update
sudo apt-get dist-upgrade
```

After that I rebooted it and enabled the serial port in the configuration GUI and rebooted again.
All the configuration seemed correct, and also the rights access to the port.
I linked the TX and RX GPIO pins.
I copied my code and executed it, with the same result, only sending, no receiveing.
I tried executing it with sudo: same result.

I executed it again with normal privileges and while it was executing, I launched the python script I told you in my first message, and then this happened:
```
pi@raspberrypi:~/Desktop/linux-arm2 $ ./TestSerial 1
Sending: 23/04/2019 09:13:54
Sending: 23/04/2019 09:13:54
Sending: 23/04/2019 09:13:55
Sending: 23/04/2019 09:13:55
Sending: 23/04/2019 09:13:56
Sending: 23/04/2019 09:13:56
Sending: 23/04/2019 09:13:57
Sending: 23/04/2019 09:13:57
Sending: 23/04/2019 09:13:58
Sending: 23/04/2019 09:13:58
Sending: 23/04/2019 09:13:59
Sending: 23/04/2019 09:13:59
Sending: 23/04/2019 09:14:00
(here the python script is launched in another window)
Received: 10:589 09:10:249:10:223/04/2019 09:10:2432323/04/2019 09:23/04/2019 09:11:0010:23/23/04/2019 09:11:0104223/04/2019 09:10:263/04/2019 09:10:25/2023/04/2019 09223/04/2019 09:11:013/04/2019 09:10:59:10:2519 023/023/04/2019 09:11:0023/04/2019 09:13:5410:589 09:10:249:10:223/04/2019 09:10:2432323/04/2019 09:23/04/2019 09:11:0010:23/23/04/2019 09:11:0104223/04/2019 09:10:263/04/2019 09:10:25/2023/04/2019 09223/04/2019 09:11:013/04/2019 09:10:59:10:2519 023/023/04/2019 09:11:0023/04/2019 09:13:5410:589 09:10:249:10:223/04/2019 09:10:2432323/04/2019 09:23/04/2019 09:11:0010:23/23/04/2019 09:11:0104223/04/2019 09:10:263/04/2019 09:10:25/2023/04/2019 09223/04/2019 09:11:013/04/2019 09:10:59:10:2519 023/023/04/2019 09:11:0023/04/2019 09:13:5410:589 09:10:249:10:223/04/2019 09:10:2432323/04/2019 09:23/04/2019 09:11:0010:23/23/04/2019 09:11:0104223/04/2019 09:10:263/04/2019 09:10:25/2023/04/2019 09223/04/2019 09:11:013/04/2019 09:10:59:10:2519 023/023/04/2019 09:11:0023/04/2019 09:13:5410:589 09:10:249:10:223/04/2019 09:1
Received: 13:5632323/04/2019 09:23/04/2019 09:11:0010:23/23/04/2019 09:11:0123/04/2019 09:13:5804223/04/223/04/2019 09:13:57019 023/04/2019 09:14:009:123/04/2019 09:13:550:23/04/2019 09:13:55263/04/2019 09:10:25/2023/04/2019 09223/04/2019 09:11:013/04/2019 09:23/04/2019 09:13:5610:59:10:2519 023/023/04/2019 09:11:0023/04/2019 09:13:5410:589 09:10:249:10:223/0423/04/2019 09:1323/04/2019 09:13:59:59/2023/04/2019 09:13:5419 09:10:2423/04/223/04/2019 09:13:58019 0923/04/2019 09:13:5Write counter: 0 

Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Sending: 23/04/2019 09:14:00
Received: 23/04/2019 09:14:00
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Received: 
Sending: 23/04/2019 09:14:01
Received: 23/04/2019 09:14:01
Received: 
Received: 
Received: Write counter: 1 

Received: 
Received: 
Received: 
Received: 
Received: 
```

As you can see, the moment I executed the python code, all the messages from my two previous tests were received (you can see that for the time of the messages). It is like if they were buffered somewhere until the python code pushed them.

I think it is not a matter of access rights, but I do not know how to solve it.

I don't want you to spend much more time in this, but if you think of another possible test, I will be happy to try it.

Thank you for your support!

**Comment by teseosoft** [comment]
Thinking about the possibility that the python code enables the serial port in some way I have come to this command to output the serial port configuration:
`stty -F /dev/ttyS0 -a`

When executed after a reboot, this is the output:
```
speed 9600 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```
When executed after the .Net Core code, the only change is the baud rate to 115200.

And when executed after the python script, this is the output:
```
speed 115200 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 0; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt
-echoctl -echoke -flusho -extproc
```

These are the differences:
min = 0 (instead of 1)
-icrnl
-onlcr
-isig -icanon -iexten -echo -echoe -echoctl

I will test them individually, but do you think one of these difference could be the reason?

**Comment by teseosoft** [comment]
I have seen that the options **-icanon -echo** are the ones that made the port work as expected.
If before my code I launch the next command:
`stty -F /dev/ttyS0 -icanon -echo`

Then the code works as expected.

Is it possible to enable these options from your code?
If not, do you think is something useful to be added?

Thanks a lot for your help!

**Comment by Ellerbach** [comment]
> I have seen that the options -icanon -echo are the ones that made the port work as expected.
> If before my code I launch the next command:
> stty -F /dev/ttyS0 -icanon -echo
> Then the code works as expected.
> Is it possible to enable these options from your code?
> If not, do you think is something useful to be added?
> Thanks a lot for your help!

Thanks a lot for the details and the investigation. Really useful! Yes, I guess I should be able to setup what is missing. Not sure why it's missing. Except couple of days/weeks before I'll do it. I'll need a bit of time before being able to work on this project.

**Comment by teseosoft** [comment]
Don't worry, take your time and I'll be here to test it once is ready.

Thank you!

**Comment by Ellerbach** [comment]
> Don't worry, take your time and I'll be here to test it once is ready.
> Thank you!

@teseosoft, I fixed it. I Added then full support for the Termios structure and all flags. So if there is any issue, I'll be able to change and adjust. So if anyone needs to adjust any other element, that will make my life easier. Nuget package being updated right now as well. 
I managed to reproduce the initial state with the latest Raspbian and deactivating the console login and activating the serial port. So I would had anyway faced it at some point.
Please let me know how it will go so if all ok, I'll close the PR. And thanks again for the deep dive!

**Comment by teseosoft** [comment]
Thanks a lot @Ellerbach!
It works like a charm!
You can indeed close the issue.

Just a small doubt: if I would want to change any parameter of the serial port, can it be done now from your code or did you "just" changed the default options?
If yes, could you send a small example, like changing the parity or the echo?
Thank you again for solving my problem!

**Comment by Ellerbach** [comment]
> It works like a charm!

Great news :-)



> Just a small doubt: if I would want to change any parameter of the serial port, can it be done now from your code or did you "just" changed the default options?

The basic code is this one: 
```csharp
            byte[] termiosData = new byte[Marshal.SizeOf(typeof(Termios))];
            Libc.tcgetattr(fd, termiosData);
            Termios terminos = TermiosHelpers.fromBytes(termiosData);
            // Set ICANON off
            terminos.LocalFalg = terminos.LocalFalg & (~(uint)LocalFlags.ICANON);
            // Set ECHO off
            terminos.LocalFalg = terminos.LocalFalg & (~(uint)LocalFlags.ECHO);
            terminos.LocalFalg = terminos.LocalFalg & (~(uint)LocalFlags.ECHOE);
            terminos.LocalFalg = terminos.LocalFalg & (~(uint)LocalFlags.ECHOCTL);
            terminos.LocalFalg = terminos.LocalFalg & (~(uint)LocalFlags.IEXTEN);
            terminos.LocalFalg = terminos.LocalFalg & (~(uint)LocalFlags.ISIG);            
            termiosData = TermiosHelpers.getBytes(terminos);
```

I may add in couple of days the possibility to do it high level directly in the SerialDevice class. So far, if you want to do it, it's manual like that in the C# code.

**Comment by Ellerbach** [comment]
@teseosoft, I did an update an fully implement the StopBits, BaudRate, Hanshake, Parity, DataBits. I've tested it and it seems to work for me. A new nuget 1.3.0 has been publised as well. Your feedback will be welcome

**Comment by teseosoft** [comment]
That's great!
With what you did it was more than enough for my current project, but with this it adds a lot of flexibility for other applications!
I will test it next week and I will tell you if I see something.
Thank you again for all!

**Comment by teseosoft** [comment]
Hello!
I have tested it (not intensevly) and everything seems to work ok, thanks!

Nevertheless, I detected a side effect...
I use your code in a program that I compile for windows and for linux, using your code for the linux part.
But when I updated your package to the 1.2.1 or 1.3.0, the following error appear when I execute the code under Windows (even when the serial device lines from your code are not actually executed):

`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'NetCoreSerial, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

If I rollback to 1.1.1 this error does not appear.
Do you know if you can make this error go away so I can use the same code for Windows and Linux?
Thanks!

**Comment by Ellerbach** [comment]
> I use your code in a program that I compile for windows and for linux, using your code for the linux part.
> But when I updated your package to the 1.2.1 or 1.3.0, the following error appear when I execute the code under Windows (even when the serial device lines from your code are not actually executed):

It seems weird, I tested built for Linux only. I'll run couple of tests to see what's happening. I did built as well for Windows but I Don't have this issue. Is it when you run the code on Windows that you get this issue (I guess with a brunch depending if you're on Windows or Linux)?

**Comment by teseosoft** [comment]
My bad!!!
I forgot to copy the new NetCoreSriall.dll and was using the old one (1.1.1)...
Everything is working now!
Sorry for this and thank you for all!

**Comment by Ellerbach** [comment]
> My bad!!!
> I forgot to copy the new NetCoreSriall.dll and was using the old one (1.1.1)...
> Everything is working now!
> Sorry for this and thank you for all!

Great news! Enjoy the new features as well ;-)
