### ISSUE TITLE
Serial port names - ttyPS*

### ISSUE THREAD

**Issue by kubafracko** [Ellerbach/serialapp#13]
This is very nice library but there is another one serial port naming policy in linux. The serial port name starts with ttyPS... sometimes. This particular case has happened on Zynq Linux from Xilinx.

```sh
[19:03][root@buildroot][~] $ setserial /dev/ttyPS0
/dev/ttyPS0, UART: undefined, Port: 0x0000, IRQ: 26
[19:03][root@buildroot][~] $ setserial /dev/ttyPS1
/dev/ttyPS1, UART: undefined, Port: 0x0000, IRQ: 27
[19:04][root@buildroot][~] $
```

Thank you for your effort

**Comment by Ellerbach** [comment]
Thanks for the feedback, I will add this one in the list then. In the mean time, you can open any serial with the full name, you don't need to go thru the function which gives the available ports. Open it directly with the full name.

**Comment by kubafracko** [comment]
Hey, thank you for your fast reply! Yes, I know that I can open port by its full name. I only shared my little part of knowledge ;)

**Comment by Ellerbach** [comment]
Thanks again for the feedback, I've intergrated, Nuget on it's way as well.
