### ISSUE TITLE
SerialDevice.GetPortNames Not returning Ports

### ISSUE THREAD

**Issue by Dicipulofer** [Ellerbach/serialapp#14]
I'm  trying to use in Mac Os Mojave 10.14.5 and it not working.

The function GetPortNames always return null, and it appear not working correctly.

 var ports = SerialDevice.GetPortNames();

**Comment by Ellerbach** [comment]
What is the port name you want to access?
If you know it, you can always use the string directly. 
I will check on a Mac in about 2 weeks when I will have access to one and will have what I need to test.

**Comment by Ellerbach** [comment]
Thank you for your patience, it is fixed now and working for MacOS. You should see all the serial port available.
Just install the package 1.3.2 and you'll be good to go.
