### ISSUE TITLE
Not being able to read from buffer on sending a command request

### ISSUE THREAD

**Issue by ankit-h** [Ellerbach/serialapp#7]
Hello, 
I am connecting to one of our device using serial port and requesting some data from it and I am using the first approach that is given in Readme. I am using a serial port sniffer to check the buffers and I can see the device sending some data into the buffer however it is not being read/ read event not being fired ever. I have just added the code to write to the serial port in Program.cs as given below. Any idea if I am missing something?

... Same code as is....
 Console.WriteLine("Yes, we have the embedded serial port available, opening it");
            SerialDevice mySer = new SerialDevice("/dev/ttyS0", BaudRate.B1152000);
            mySer.DataReceived += MySer_DataReceived;
            mySer.Open();
            **var command = string.Concat((char)1, "i20100");
            Console.WriteLine($"Writing following command: {command}");
            mySer.Write(System.Text.Encoding.UTF8.GetBytes(command));**
            while (!Console.KeyAvailable)
                ;
            mySer.Close();

.... rest of the code.

**Comment by Ellerbach** [comment]
Hi, have you checked the baud rate, number of bit, bit stop? 
I know it seems basic but sometimes issues are realated to that. 
And check as well the voltage of the device and the dongle you are using.
Finally, is the serial port /dev/ttyS0? or is there any other serial port used?

**Comment by ankit-h** [comment]
Hey, I did check the baud rate and other settings but doesn't seem to work for me.
I also checked with cutecom client and was able to successfully connect and get response with same serial port settings.

Additional Information:
1. The second approach in readme(by building dependencies) works well for me. And if try that approach first and go back to using DLLImport approach, it somehow starts to work.
2. I also installed VS code and tried debugging the code, I found out that the debug control never move ahead of Libc.Read() line in SerialDevice.cs.

Not sure what is being missed. Any help will be highly appreciated. thanks!

**Comment by Ellerbach** [comment]
hum, not sure what's happening. It should just work fine. There is no mistery and the code is straight forward. It woks perfectly for me on Linux and Mac without any issue. 
Do you have enought priviledges to run the code? have you tried to run it in sudo mode?

**Comment by Ellerbach** [comment]
I'll close this issue as no news from you. Please reach out if still any issue.
